### Adress show all
GET http://localhost:3001/api/persons

### Get a specific person
GET http://localhost:3001/api/persons/4

### Delete a specific person
DELETE http://localhost:3001/api/persons/684fd93ca67023f841ad80cf

### Create a new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Zlartibart Fass",
  "number": "+49 30 113 23 44"
}

### try to create a person without a name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "Nase": "Zlartibart Fass",
  "number": "+49 30 113 23 44"
}

### try to create a person without a number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Zlartibart Fass",
  "bummer": "+49 30 113 23 44"
}

### Notes
### post an invalid note
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2ODVlNTY2YmMyMzYyODg3ODNkOTllNDAiLCJpYXQiOjE3NTE0NTQzODMsImV4cCI6MTc1MTQ1Nzk4M30.y3dQU6wgdL6aZ3vSDaZSS4h4Sik3KsHMt8kYLIRrmys

{
  "inhalt": "Die kuh rennt um See rum.",
  "important": "false"
}

### post a valid note
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2ODVlNTY2YmMyMzYyODg3ODNkOTllNDAiLCJpYXQiOjE3NTE0NTQzODMsImV4cCI6MTc1MTQ1Nzk4M30.y3dQU6wgdL6aZ3vSDaZSS4h4Sik3KsHMt8kYLIRrmys

{
  "content": "Fackelmann und Blasehase",
  "important": "false"
}

#### get all notes
GET http://localhost:3001/api/notes

#### delete a specific node
DELETE http://localhost:3001/api/notes/684bf9ddc649fd4b5bcbfeac
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2ODVlNTY2YmMyMzYyODg3ODNkOTllNDAiLCJpYXQiOjE3NTE0NTQzODMsImV4cCI6MTc1MTQ1Nzk4M30.y3dQU6wgdL6aZ3vSDaZSS4h4Sik3KsHMt8kYLIRrmys

#### update a specific node
PUT http://localhost:3001/api/notes/68625829a43abfb9db7aeb46
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2ODVlNTY2YmMyMzYyODg3ODNkOTllNDAiLCJpYXQiOjE3NTE4NzEzNjEsImV4cCI6MTc1MTg3NDk2MX0.692wbotNQMf3OLtBMQJvOlWiVU8NY7VHgSBI5wNeLo4

{
  "content": "und nu ma wat völlich andres",
  "important": "true"
}

#### get all blogposts
GET http://localhost:3001/api/blogs

#### add a blog post
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Was sich bei den VmWare Alternativen gerade tut",
  "author": "Jens Söldner",
  "url": "https://www.heise.de/hintergrund/Was-sich-bei-den-VMware-Alternativen-gerade-tut-10452540.html",
  "likes": 0
}

#### add a user
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "admin",
  "name": "superuser",
  "password": "BlahFasel"
}

#### show a list of users
GET http://localhost:3001/api/users

#### login as superuser
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "admin",
  "password": "BlahFasel"
}